#!/bin/bash

#URL=http://requestb.in/rlh4znrl
#echo "----> Posting to $URL ..."
#curl \
#  -X 'POST' \
#  -F "repository=$1" \
#  -F "revision=$2" \
#  -F "username=$3" \
#  -F "fingerprint=$4" \
#  -F contents=@- \
#  --silent $URL

REPO=/opt/majordomus/majord-data/git/$1

echo "----> Receiving repository $1 ..."
mkdir -p $REPO && cat | tar -x -C $REPO

echo "----> Stored new/updated files in $REPO" 

if [ -f "$REPO/Dockerfile" ]; then
	echo "----> Dockerfile"
else
	echo "----> Something else"
fi